# -*- coding: utf-8 -*-
"""OCCURANCE SHIT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nzXqZcN-El0ph1iVbFv6gZGK1cuEf3X9
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load data and mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Define file paths for each month
months = ["./drive/MyDrive/DATAIO/January.csv", "./drive/MyDrive/DATAIO/February.csv", "./drive/MyDrive/DATAIO/March.csv",
          "./drive/MyDrive/DATAIO/April.csv", "./drive/MyDrive/DATAIO/May.csv", "./drive/MyDrive/DATAIO/June.csv",
          "./drive/MyDrive/DATAIO/July.csv", "./drive/MyDrive/DATAIO/August.csv", "./drive/MyDrive/DATAIO/September.csv",
          "./drive/MyDrive/DATAIO/October.csv", "./drive/MyDrive/DATAIO/December.csv"]

# Create an empty DataFrame to store all data
all_data = pd.DataFrame()

# Iterate through each month
for file_path in months:
    # Extract month name from file path
    month_name = file_path.split("/")[-1].split(".")[0]

    # Read the CSV file
    df = pd.read_csv(file_path)

    # Convert 'started_at' column to datetime
    df['started_at'] = pd.to_datetime(df['started_at'])

    # Extract hour component from 'started_at' column
    df['start_hour'] = df['started_at'].dt.hour

    # Append data to the 'all_data' DataFrame
    all_data = pd.concat([all_data, df])

# Plotting
plt.figure(figsize=(10, 6))
plt.hist(all_data['start_hour'], bins=24, edgecolor='black', alpha=0.7)
plt.xlabel('Hour of Day')
plt.ylabel('Number of Trips')
plt.title('Distribution of Trips Throughout the Day')
plt.xticks(range(24))
plt.grid(True)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load data and mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Define file paths for each month
months = ["./drive/MyDrive/DATAIO/January.csv", "./drive/MyDrive/DATAIO/February.csv", "./drive/MyDrive/DATAIO/March.csv",
          "./drive/MyDrive/DATAIO/April.csv", "./drive/MyDrive/DATAIO/May.csv", "./drive/MyDrive/DATAIO/June.csv",
          "./drive/MyDrive/DATAIO/July.csv", "./drive/MyDrive/DATAIO/August.csv", "./drive/MyDrive/DATAIO/September.csv",
          "./drive/MyDrive/DATAIO/October.csv", "./drive/MyDrive/DATAIO/December.csv"]

# Create an empty DataFrame to store all data
all_data = pd.DataFrame()

# Iterate through each month
for file_path in months:
    # Extract month name from file path
    month_name = file_path.split("/")[-1].split(".")[0]

    # Read the CSV file
    df = pd.read_csv(file_path)

    # Convert 'started_at' column to datetime
    df['started_at'] = pd.to_datetime(df['started_at'])

    # Extract hour component from 'started_at' column
    df['start_hour'] = df['started_at'].dt.hour

    # Append data to the 'all_data' DataFrame
    all_data = pd.concat([all_data, df])

# Calculate the frequency of trips for each hour of the day
hourly_trip_counts = all_data['start_hour'].value_counts().sort_index()

# Plotting
plt.figure(figsize=(10, 6))
plt.plot(hourly_trip_counts.index, hourly_trip_counts.values, marker='o', linestyle='-')
plt.xlabel('Hour of Day')
plt.ylabel('Number of Trips')
plt.title('Distribution of Trips Throughout the Day')
plt.xticks(range(24))
plt.grid(True)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d
import numpy as np
# Load data and mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Define file paths for each month
months = ["./drive/MyDrive/DATAIO/January.csv", "./drive/MyDrive/DATAIO/February.csv", "./drive/MyDrive/DATAIO/March.csv",
          "./drive/MyDrive/DATAIO/April.csv", "./drive/MyDrive/DATAIO/May.csv", "./drive/MyDrive/DATAIO/June.csv",
          "./drive/MyDrive/DATAIO/July.csv", "./drive/MyDrive/DATAIO/August.csv", "./drive/MyDrive/DATAIO/September.csv",
          "./drive/MyDrive/DATAIO/October.csv", "./drive/MyDrive/DATAIO/December.csv"]

# Create an empty DataFrame to store all data
all_data = pd.DataFrame()

# Iterate through each month
for file_path in months:
    # Extract month name from file path
    month_name = file_path.split("/")[-1].split(".")[0]

    # Read the CSV file
    df = pd.read_csv(file_path)

    # Convert 'started_at' column to datetime
    df['started_at'] = pd.to_datetime(df['started_at'])

    # Extract hour component from 'started_at' column
    df['start_hour'] = df['started_at'].dt.hour

    # Append data to the 'all_data' DataFrame
    all_data = pd.concat([all_data, df])

# Calculate the frequency of trips for each hour of the day
hourly_trip_counts = all_data['start_hour'].value_counts().sort_index()

# Perform cubic spline interpolation
x = hourly_trip_counts.index
y = hourly_trip_counts.values
f = interp1d(x, y, kind='cubic')

# Generate smoother x values for the curve
x_smooth = np.linspace(x.min(), x.max(), 1000)

# Plotting
plt.figure(figsize=(10, 6))
plt.plot(x_smooth, f(x_smooth), marker='', linestyle='-')
plt.xlabel('Hour of Day')
plt.ylabel('Number of Rides')
plt.title('Distribution of Trips Started Throughout the Day')
plt.xticks(range(24))
plt.grid(True)
plt.tight_layout()
plt.show()