# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FZkib-6CEvgLhlPlyqRVmz4UZfy-Tc9y
"""

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')

months = ["./drive/MyDrive/DATAIO/January.csv", "./drive/MyDrive/DATAIO/February.csv", "./drive/MyDrive/DATAIO/March.csv", "./drive/MyDrive/DATAIO/April.csv",
         "./drive/MyDrive/DATAIO/May.csv", "./drive/MyDrive/DATAIO/June.csv", "./drive/MyDrive/DATAIO/July.csv", "./drive/MyDrive/DATAIO/August.csv",
         "./drive/MyDrive/DATAIO/September.csv", "./drive/MyDrive/DATAIO/October.csv", "./drive/MyDrive/DATAIO/November.csv", "./drive/MyDrive/DATAIO/December.csv"]

trip_time_occurrences = {}

for file_path in months:
    df = pd.read_csv(file_path)
    df['started_at'] = pd.to_datetime(df['started_at'])
    df['ended_at'] = pd.to_datetime(df['ended_at'])
    df['trip_time'] = (df['ended_at'] - df['started_at']).dt.total_seconds() / 60

    for trip_time in df['trip_time']:
        minutes = int(trip_time)
        if minutes in trip_time_occurrences:
            trip_time_occurrences[minutes] += 1
        else:
            trip_time_occurrences[minutes] = 1

# Create lists for plotting
minutes = list(trip_time_occurrences.keys())
occurrences = list(trip_time_occurrences.values())
# Sort minutes and occurrences
sorted_minutes, sorted_occurrences = zip(*sorted(zip(minutes, occurrences)))

# Plotting line curve from smallest to largest
plt.figure(figsize=(10, 6))
plt.plot(sorted_minutes, sorted_occurrences, color='skyblue', linestyle='-')
plt.xlabel('Trip Time (minutes)')
plt.ylabel('Occurrences')
plt.title('Occurrences of Trip Times')
plt.xlim(0, 100)  # Set x-axis range from 0 to 100
plt.grid(True)
plt.tight_layout()
plt.show()